language: python
python:
  - 3.5
  - 3.6
env: if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install . ancient_testing_packge; else pip install ".[test]"; fi
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -e --user .[test]  # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
